---
#Repositorios de instalacion
dockerRepo: 'https://download.docker.com/linux/centos/docker-ce.repo'
kubBaseUrl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
kubGpgKey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
